# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.16"
  armv7: "ghcr.io/home-assistant/armv7-base:3.17"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Addon: Minecraft Server Bedrock"
  org.opencontainers.image.description: "This addon runs a minecraft server bedrock edition. It can be fully configured in the UI."
  org.opencontainers.image.source: "https://github.com/aph-le/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
