# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HA Spawn Point Bedrock
version: "0.0.1"
slug: ha-spawn-point-bedrock
description: Minecraft Server Addon Bedrock Edition
#url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - amd64
  - aarch64
ports:
  19132/udp: "19132"
ports_description:
  19132/udp: Minecraft Server Port
init: false
map:
  - share:rw
options:
  eula: true
  server_name: MC Spawn Server
  version: LATEST
  level_name: MC Spawn World
  level_gamemode: survival
  level_difficulty: easy
schema:
  eula: bool
  server_name: str
  version: "match(^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)|(LATEST)$)"
  level_name: str
  level_gamemode: list(survival|creative|adventure)
  level_difficulty: list(peaceful|easy|normal|hard)
  level_seed: "str?"
  online_mode: bool?
  enable_lan_visibilty: bool?
#image: "ghcr.io/home-assistant/{arch}-addon-example"
