# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HA Spawn Point Bedrock
version: "0.0.2"
slug: ha-spawn-point-bedrock
description: Minecraft Server Addon Bedrock Edition
#url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - amd64
  - aarch64
ports:
  19132/udp: "19132"
ports_description:
  19132/udp: Minecraft Server Port
host_network: true
init: false
map:
  - addons:rw
options:
  eula: true
  server_name: Spawn Point Bedrock Server
  version: LATEST
  level_name: Spawn Point Bedrock
  max_players: 10
  gamemode: survival
  difficulty: easy
schema:
  eula: bool
  server_name: str
  version: "match(^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)|(LATEST)$)"
  level_name: str
  max_players: int(1,)
  gamemode: list(survival|creative|adventure)
  difficulty: list(peaceful|easy|normal|hard)
  level_seed: "str?"
  max_threads: int(1,8)?
  online_mode: bool?
  enable_lan_visibility: bool?
  enable_port_proxy: bool?
  allow_list: bool?
  allow_user:
    - username: str?
      xuid: str?
#image: "ghcr.io/home-assistant/{arch}-addon-example"
