# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HA Spawn Point Bedrock
version: "2023.12.1"
slug: ha-spawn-point-bedrock
description: Minecraft Server Addon Bedrock Edition
#url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - amd64
  - aarch64
#ports:
#  19132/udp: 19132
#ports_description:
#  19132/udp: Minecraft Server Port
host_network: true
init: false
map:
  - addons:rw
tmpfs: true
options:
  eula: true
  server_name: Spawn Point Bedrock Server
  version: LATEST
  level_name: Spawn Point Bedrock
  max_players: 10
  gamemode: survival
  difficulty: easy
  allow_list: false
  allow_user:
    - name: "PlayerOne"
      xuid: "1234567890"
      ignoresPlayerLimit: "false"
  default_player_permission_level: member
  permissions_user:
    - xuid: "1234567890"
      permission: "operator"
schema:
  eula: bool
  server_name: str
  version: "match(^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)|(LATEST)$)"
  level_name: str
  max_players: int(1,)
  gamemode: list(survival|creative|adventure)
  difficulty: list(peaceful|easy|normal|hard)
  allow_list: bool
  allow_user:
    - name: str
      xuid: "str?"
      ignoresPlayerLimit: bool
  default_player_permission_level: list(operator|member|visitor)
  permissions_user:
    - xuid: str
      permission: str
  level_seed: "str?"
  max_threads: "int(1,8)?"
  online_mode: "bool?"
  enable_lan_visibility: "bool?"
  enable_port_proxy: "bool?"
#image: "ghcr.io/aph-le/{arch}-addon-spawn-point-bedrock"
